import{a as E,i as B,s as $}from"./assets/vendor-da73009b.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(t){if(t.ep)return;t.ep=!0;const n=r(t);fetch(t.href,n)}})();const I="23963114-6d0d5d874ae460d9125bacd21",v="https://pixabay.com/api/";let d=1;async function h(e,o=!1){o&&(d=1);const r=`${v}?key=${I}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${d}`;try{const s=await E.get(r);if(s.status!==200)throw new Error(`Error: ${s.statusText}`);return d+=1,s.data}catch(s){return console.error("Fetch error:",s),{hits:[],totalHits:0}}}let u;document.querySelector(".container");const y=document.querySelector(".gallery"),m=document.getElementById("loader"),g=document.getElementById("load-more");function p(e){const o=e.map(r=>`<li class="gallery-item">
      <a class="gallery-link" href="${r.webformatURL}">
        <img 
          class="gallery-image" 
          width="360"
          src="${r.largeImageURL}" 
          alt="${r.tags}" 
        />
      </a>
      <ul class='description'>
        <li class="info-title"><strong>Likes</strong><span class="info-text"> ${r.likes}</span></li>
        <li class="info-title"><strong>Views</strong><span class="info-text"> ${r.views}</span></li>
        <li class="info-title"><strong>Comments</strong><span class="info-text"> ${r.comments}</span></li>
        <li class="info-title"><strong>Downloads</strong><span class="info-text"> ${r.downloads}</span></li>
      </ul>
    </li>`).join("");y.insertAdjacentHTML("beforeend",o)}function i(e){B.error({title:"Error",message:e})}function S(){y.innerHTML=""}function L(){m.style.display="block"}function w(){m.style.display="none"}function M(){g.style.display="block"}function b(){g.style.display="none"}function q(){u=new $(".gallery a",{captionsData:"alt",captionDelay:250})}function x(){u?u.refresh():q()}function P(){const{height:e}=y.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}const C=document.querySelector(".form"),O=document.querySelector(".search-input"),f=document.getElementById("load-more"),a=document.getElementById("loading-text");document.querySelector("#load-more").textContent="Load more";let l="";C.addEventListener("submit",k);f.addEventListener("click",A);async function k(e){if(e.preventDefault(),l=O.value.trim(),!l){i("Please enter a search term");return}S(),b(),L(),a.style.display="block";try{const o=await h(l,!0);o.hits.length===0?i("Sorry, there are no images matching your search query. Please try again!"):(p(o.hits),M(),x())}catch(o){i("An error occurred while fetching images"),console.error(o)}finally{w(),a.style.display="none"}}async function A(){L(),f.style.display="none",a.style.display="block";try{const e=await h(l);e.hits.length===0?(i("We're sorry, but you've reached the end of search results."),b()):(p(e.hits),x(),P())}catch(e){i("An error occurred while fetching images"),console.error(e)}finally{w(),f.style.display="block",a.style.display="none"}}document.addEventListener("DOMContentLoaded",R);function R(){const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
