import{a as $,i as v,s as S}from"./assets/vendor-da73009b.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const u of n.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function r(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(o){if(o.ep)return;o.ep=!0;const n=r(o);fetch(o.href,n)}})();const M="23963114-6d0d5d874ae460d9125bacd21",q="https://pixabay.com/api/";let f=1;async function m(e,t=!1){t&&(f=1);const r=`${q}?key=${M}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${f}`;try{const s=await $.get(r);if(s.status!==200)throw new Error(`Error: ${s.statusText}`);return f+=1,s.data}catch(s){return console.error("Fetch error:",s),{hits:[],totalHits:0}}}let y;document.querySelector(".container");const h=document.querySelector(".gallery"),g=document.getElementById("loader"),p=document.getElementById("load-more");function L(e){const t=e.map(r=>`<li class="gallery-item">
      <a class="gallery-link" href="${r.webformatURL}">
        <img 
          class="gallery-image" 
          width="360"
          src="${r.largeImageURL}" 
          alt="${r.tags}" 
        />
      </a>
      <ul class='description'>
        <li class="info-title"><strong>Likes</strong><span class="info-text"> ${r.likes}</span></li>
        <li class="info-title"><strong>Views</strong><span class="info-text"> ${r.views}</span></li>
        <li class="info-title"><strong>Comments</strong><span class="info-text"> ${r.comments}</span></li>
        <li class="info-title"><strong>Downloads</strong><span class="info-text"> ${r.downloads}</span></li>
      </ul>
    </li>`).join("");h.insertAdjacentHTML("beforeend",t)}function l(e){v.error({title:"Error",message:e})}function H(){h.innerHTML=""}function w(){g.style.display="block"}function b(){g.style.display="none"}function x(){p.style.display="block"}function E(){p.style.display="none"}function P(){y=new S(".gallery a",{captionsData:"alt",captionDelay:250})}function B(){y?y.refresh():P()}function C(){const{height:e}=h.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}const O=document.querySelector(".form"),A=document.querySelector(".search-input"),I=document.getElementById("load-more"),c=document.getElementById("loading-text");document.querySelector("#load-more").textContent="Load more";let a="",d=0,i=0;O.addEventListener("submit",R);I.addEventListener("click",k);async function R(e){if(e.preventDefault(),a=A.value.trim(),!a){l("Please enter a search term");return}H(),E(),w(),c.style.display="block";try{const t=await m(a,!0);d=t.totalHits,i=t.hits.length,i===0?l("Sorry, there are no images matching your search query. Please try again!"):(L(t.hits),B(),i<d&&x())}catch(t){l("An error occurred while fetching images"),console.error(t)}finally{b(),c.style.display="none"}}async function k(){w(),I.style.display="none",c.style.display="block";try{const e=await m(a);i+=e.hits.length,i>=d?(l("We're sorry, but you've reached the end of search results."),E()):(L(e.hits),B(),C(),i<d&&x())}catch(e){l("An error occurred while fetching images"),console.error(e)}finally{b(),c.style.display="none"}}document.addEventListener("DOMContentLoaded",D);function D(){const e=document.querySelector(".gallery-item");if(e){const t=e.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
